//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Challenge = new HashSet<Challenge>();
            this.Challenge1 = new HashSet<Challenge>();
            this.Highscore = new HashSet<Highscore>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Challenge> Challenge { get; set; }
        public virtual ICollection<Challenge> Challenge1 { get; set; }
        public virtual ICollection<Highscore> Highscore { get; set; }
    }
}
