//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHALLENGES
    {
        public int ID { get; set; }
        public string Challenger { get; set; }
        public string Challenged { get; set; }
        public string Sudoku { get; set; }
        public Nullable<bool> Completed { get; set; }
    }
}
