//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public int ID { get; set; }
        public Nullable<int> ChallengerID { get; set; }
        public Nullable<int> ChallengedID { get; set; }
        public Nullable<int> SudokuID { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Sudoku Sudoku { get; set; }
    }
}
