//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HARD
    {
        public string Name { get; set; }
        public string Difficulty { get; set; }
        public long Score { get; set; }
    }
}
