//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SudokuAppHrbrEntities : DbContext
    {
        public SudokuAppHrbrEntities()
            : base("name=SudokuAppHrbrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Challenge> Challenge { get; set; }
        public DbSet<Highscore> Highscore { get; set; }
        public DbSet<Sudoku> Sudoku { get; set; }
    }
}
