//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovProektPMUEntities : DbContext
    {
        public KursovProektPMUEntities()
            : base("name=KursovProektPMUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Challenge> Challenge { get; set; }
        public DbSet<Highscore> Highscore { get; set; }
        public DbSet<Sudoku> Sudoku { get; set; }
        public DbSet<EASY> EASY { get; set; }
        public DbSet<EVIL> EVIL { get; set; }
        public DbSet<HARD> HARD { get; set; }
        public DbSet<MEDIUM> MEDIUM { get; set; }
        public DbSet<TOP_SCORES> TOP_SCORES { get; set; }
    }
}
