//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMUProektServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudoku
    {
        public Sudoku()
        {
            this.Challenge = new HashSet<Challenge>();
        }
    
        public int ID { get; set; }
        public string Difficulty { get; set; }
        public Nullable<int> LRU { get; set; }
        public string Puzzle { get; set; }
    
        public virtual ICollection<Challenge> Challenge { get; set; }
    }
}
